export const allProducts = [
  { id: 1, name: 'Praliny Różane', price: 85, badge: null, category: 'Edycje Limitowane', new: false, collection: 'Edycje Limitowane', description: 'Delikatne praliny z nadzieniem o smaku różanym, otoczone białą czekoladą.', image: 'https://placehold.co/300x300/f2e8e6/333333?text=Praliny+Różane' },
  { id: 2, name: 'Złota Kolekcja', price: 140, badge: 'NOWOŚĆ', category: 'Kolekcje Premium', new: true, collection: 'Kolekcje Premium', description: 'Ekskluzywny zestaw pralin w złotych opakowaniach, idealny na prezent.', image: 'https://placehold.co/300x300/e6d8a8/333333?text=Złota+Kolekcja' },
  { id: 3, name: 'Karmel i Sól', price: 65, badge: null, category: 'Klasyki', new: false, collection: 'Klasyki', description: 'Połączenie słodkiego karmelu i szczypty soli morskiej w mlecznej czekoladzie.', image: 'https://placehold.co/300x300/d1cda8/333333?text=Karmel+i+Sól' },
  { id: 4, name: 'Klasyczne Trufle', price: 70, badge: null, category: 'Klasyki', new: false, collection: 'Klasyki', description: 'Aksamitne trufle z ciemnej czekolady, obtoczone w kakao.', image: 'https://placehold.co/300x300/bfa89e/333333?text=Klasyczne+Trufle' },
  { id: 5, name: 'Biała z Maliną', price: 45, badge: null, category: 'Czekolady', new: false, collection: 'Czekolady', description: 'Tabliczka białej czekolady z liofilizowanymi malinami.', image: 'https://placehold.co/300x300/f2e6e6/333333?text=Biała+z+Maliną' },
  { id: 6, name: 'Ciemna 85%', price: 38, badge: null, category: 'Czekolady', new: false, collection: 'Czekolady', description: 'Intensywna w smaku tabliczka ciemnej czekolady o zawartości 85% kakao.', image: 'https://placehold.co/300x300/a89e9e/333333?text=Ciemna+85%' },
  { id: 7, name: 'Orzechy Laskowe', price: 55, badge: null, category: 'Praliny', new: false, collection: 'Praliny', description: 'Praliny z całymi orzechami laskowymi w mlecznej czekoladzie.', image: 'https://placehold.co/300x300/d1cda8/333333?text=Orzechy+Laskowe' },
  { id: 8, name: 'Degustacja', price: 180, badge: null, category: 'Zestawy Prezentowe', new: false, collection: 'Zestawy Prezentowe', description: 'Zestaw degustacyjny zawierający różne rodzaje naszych pralin i czekolad.', image: 'https://placehold.co/300x300/e6e6e6/333333?text=Degustacja' },
  { id: 9, name: 'Matcha & Yuzu', price: 95, badge: 'NOWOŚĆ', category: 'Edycje Limitowane', new: true, collection: 'Edycje Limitowane', description: 'Egzotyczne połączenie japońskiej herbaty matcha i cytrusowego yuzu.', image: 'https://placehold.co/300x300/e6f2e6/333333?text=Matcha+&+Yuzu' },
  { id: 10, name: 'Lawendowe Sny', price: 80, badge: null, category: 'Edycje Limitowane', new: false, collection: 'Edycje Limitowane', description: 'Praliny z nutą lawendy.', image: 'https://placehold.co/300x300/e6e6fa/333333?text=Lawendowe+Sny' },
  { id: 11, name: 'Miodowe Serce', price: 75, badge: null, category: 'Klasyki', new: false, collection: 'Klasyki', description: 'Czekoladki z płynnym miodem.', image: 'https://placehold.co/300x300/f0e68c/333333?text=Miodowe+Serce' },
  { id: 12, name: 'Wiśniowy Raj', price: 90, badge: null, category: 'Praliny', new: false, collection: 'Praliny', description: 'Praliny z wiśniami w likierze.', image: 'https://placehold.co/300x300/dc143c/333333?text=Wiśniowy+Raj' },
  { id: 13, name: 'Królewska Pomarańcza', price: 85, badge: null, category: 'Kolekcje Premium', new: false, collection: 'Kolekcje Premium', description: 'Kandyzowana skórka pomarańczy w czekoladzie.', image: 'https://placehold.co/300x300/ffa500/333333?text=Królewska+Pomarańcza' },
  { id: 14, name: 'Czekoladowa Fantazja', price: 110, badge: 'NOWOŚĆ', category: 'Nowe Kolekcje', new: true, collection: 'Nowe Kolekcje', description: 'Zestaw różnorodnych czekoladek.', image: 'https://placehold.co/300x300/d2b48c/333333?text=Czekoladowa+Fantazja' },
  { id: 15, name: 'Trufle Szampańskie', price: 120, badge: null, category: 'Kolekcje Premium', new: false, collection: 'Kolekcje Premium', description: 'Trufle z dodatkiem szampana.', image: 'https://placehold.co/300x300/fafad2/333333?text=Trufle+Szampańskie' },
  { id: 16, name: 'Pistacjowa Rozkosz', price: 95, badge: null, category: 'Praliny', new: false, collection: 'Praliny', description: 'Praliny z kremem pistacjowym.', image: 'https://placehold.co/300x300/93c572/333333?text=Pistacjowa+Rozkosz' },
  { id: 17, name: 'Malinowy Chrupek', price: 50, badge: null, category: 'Czekolady', new: false, collection: 'Czekolady', description: 'Czekolada z chrupiącymi malinami.', image: 'https://placehold.co/300x300/ffc0cb/333333?text=Malinowy+Chrupek' },
  { id: 18, name: 'Orzechowa Moc', price: 60, badge: null, category: 'Czekolady', new: false, collection: 'Czekolady', description: 'Czekolada z mieszanką orzechów.', image: 'https://placehold.co/300x300/deb887/333333?text=Orzechowa+Moc' },
  { id: 19, name: 'Kolekcja Zimowa', price: 130, badge: 'NOWOŚĆ', category: 'Nowe Kolekcje', new: true, collection: 'Nowe Kolekcje', description: 'Zimowe smaki pralin.', image: 'https://placehold.co/300x300/add8e6/333333?text=Kolekcja+Zimowa' },
  { id: 20, name: 'Letnie Orzeźwienie', price: 100, badge: null, category: 'Edycje Limitowane', new: false, collection: 'Edycje Limitowane', description: 'Owocowe praliny na lato.', image: 'https://placehold.co/300x300/ffffe0/333333?text=Letnie+Orzeźwienie' },
];

export const categories = [
  'Wszystko',
  'Edycje Limitowane',
  'Kolekcje Premium',
  'Klasyki',
  'Czekolady',
  'Praliny',
  'Zestawy Prezentowe',
  'Nowe Kolekcje',
];
